using Microsoft.JSInterop;

namespace AnkhD.Services;

public sealed class SiteLocalization(IJSRuntime js)
{
    public sealed record Language(string Code, string Locale, string Flag, string ShortName, string NativeName, bool RightToLeft = false);

    public static readonly Language[] Languages =
    [
        new("pt", "pt-BR", "🇧🇷", "PT", "Português"),
        new("en", "en-GB", "🇬🇧", "EN", "English"),
        new("es", "es-ES", "🇪🇸", "ES", "Español"),
        new("ar", "ar-EG", "🇪🇬", "AR", "العربية", true)
    ];

    private static readonly Dictionary<string, Dictionary<string, string>> Translations = new(StringComparer.Ordinal)
    {
        ["Soluções Tecnológicas"] = Row("Technology Solutions", "Soluciones Tecnológicas", "حلول تقنية"),
        ["Início"] = Row("Home", "Inicio", "الرئيسية"),
        ["Serviços"] = Row("Services", "Servicios", "الخدمات"),
        ["Projetos"] = Row("Projects", "Proyectos", "المشاريع"),
        ["Sobre"] = Row("About", "Nosotros", "من نحن"),
        ["Contato"] = Row("Contact", "Contacto", "اتصل بنا"),
        ["Fale Conosco"] = Row("Let's Talk", "Hablemos", "تواصل معنا"),
        ["Abrir menu"] = Row("Open menu", "Abrir menú", "فتح القائمة"),
        ["Fechar menu"] = Row("Close menu", "Cerrar menú", "إغلاق القائمة"),
        ["Navegação principal"] = Row("Main navigation", "Navegación principal", "التنقل الرئيسي"),
        ["Selecionar idioma"] = Row("Select language", "Seleccionar idioma", "اختيار اللغة"),
        ["Idioma atual: {0}"] = Row("Current language: {0}", "Idioma actual: {0}", "اللغة الحالية: {0}"),

        ["Tecnologia com propósito"] = Row("Technology with purpose", "Tecnología con propósito", "تقنية هادفة"),
        ["Transformamos ideias em"] = Row("We turn ideas into", "Transformamos ideas en", "نحوّل الأفكار إلى"),
        ["soluções digitais"] = Row("digital solutions", "soluciones digitales", "حلول رقمية"),
        ["de impacto."] = Row("that make an impact.", "de impacto.", "ذات أثر."),
        ["Desenvolvimento de sites, automações e sistemas sob medida para impulsionar o seu negócio."] = Row("Websites, automation and custom systems built to move your business forward.", "Sitios web, automatizaciones y sistemas a medida para impulsar su negocio.", "مواقع وأتمتة وأنظمة مخصصة لدفع أعمالك إلى الأمام."),
        ["Nossos Serviços"] = Row("Our Services", "Nuestros Servicios", "خدماتنا"),
        ["Ver Projetos"] = Row("View Projects", "Ver Proyectos", "عرض المشاريع"),
        ["Explore"] = Row("Explore", "Explorar", "استكشف"),
        ["Estratégia"] = Row("Strategy", "Estrategia", "الاستراتيجية"),
        ["Soluções pensadas para objetivos reais."] = Row("Solutions designed for real goals.", "Soluciones pensadas para objetivos reales.", "حلول مصممة لأهداف حقيقية."),
        ["Tecnologia"] = Row("Technology", "Tecnología", "التقنية"),
        ["Ferramentas modernas e resultados escaláveis."] = Row("Modern tools and scalable results.", "Herramientas modernas y resultados escalables.", "أدوات حديثة ونتائج قابلة للتوسع."),
        ["Resultado"] = Row("Results", "Resultados", "النتائج"),
        ["Foco em performance, eficiência e crescimento."] = Row("Focused on performance, efficiency and growth.", "Enfoque en rendimiento, eficiencia y crecimiento.", "تركيز على الأداء والكفاءة والنمو."),

        ["Nossos serviços"] = Row("Our services", "Nuestros servicios", "خدماتنا"),
        ["Soluções que impulsionam"] = Row("Solutions that drive", "Soluciones que impulsan", "حلول تدفع"),
        ["resultados"] = Row("results", "resultados", "النتائج"),
        ["Do primeiro contato à entrega, tecnologia pensada para resolver desafios reais do seu negócio."] = Row("From first contact to delivery, technology designed to solve real business challenges.", "Desde el primer contacto hasta la entrega, tecnología pensada para resolver retos reales de su negocio.", "من أول تواصل حتى التسليم، تقنية مصممة لحل تحديات أعمال حقيقية."),
        ["Conheça o serviço"] = Row("Explore the service", "Conozca el servicio", "اكتشف الخدمة"),
        ["Serviço"] = Row("Service", "Servicio", "الخدمة"),
        ["O que desenvolvemos"] = Row("What we build", "Lo que desarrollamos", "ما الذي نطوره"),
        ["Indicado para"] = Row("Best suited for", "Ideal para", "مناسب لـ"),
        ["Resultado esperado"] = Row("Expected outcome", "Resultado esperado", "النتيجة المتوقعة"),
        ["Como conduzimos"] = Row("How we work", "Cómo trabajamos", "كيف نعمل"),
        ["Cada projeto recebe escopo e prioridades definidos conforme o contexto do negócio."] = Row("Every project receives a scope and priorities tailored to its business context.", "Cada proyecto recibe un alcance y prioridades definidos según el contexto del negocio.", "يحصل كل مشروع على نطاق وأولويات تناسب سياق العمل."),
        ["Conversar sobre este serviço"] = Row("Discuss this service", "Hablar sobre este servicio", "ناقش هذه الخدمة"),

        ["Presença digital"] = Row("Digital presence", "Presencia digital", "الحضور الرقمي"),
        ["Sites Profissionais"] = Row("Professional Websites", "Sitios Web Profesionales", "مواقع احترافية"),
        ["Sites modernos, responsivos e otimizados para fortalecer sua presença na internet."] = Row("Modern, responsive and optimised websites that strengthen your online presence.", "Sitios modernos, responsivos y optimizados para fortalecer su presencia en internet.", "مواقع حديثة ومتجاوبة ومحسنة لتعزيز حضورك على الإنترنت."),
        ["Criamos sites institucionais e páginas de conversão que apresentam sua empresa com clareza, confiança e uma experiência consistente em qualquer tela."] = Row("We create corporate websites and conversion pages that present your business clearly and confidently on every screen.", "Creamos sitios corporativos y páginas de conversión que presentan su empresa con claridad y confianza en cualquier pantalla.", "ننشئ مواقع وصفحات تحويل تعرض شركتك بوضوح وثقة على كل شاشة."),
        ["Arquitetura de conteúdo e interface responsiva"] = Row("Content architecture and responsive interface", "Arquitectura de contenido e interfaz responsiva", "هندسة المحتوى وواجهة متجاوبة"),
        ["Performance, acessibilidade e SEO técnico"] = Row("Performance, accessibility and technical SEO", "Rendimiento, accesibilidad y SEO técnico", "الأداء وإمكانية الوصول وتحسين محركات البحث"),
        ["Formulários, métricas e integrações essenciais"] = Row("Forms, analytics and essential integrations", "Formularios, métricas e integraciones esenciales", "النماذج والتحليلات والتكاملات الأساسية"),
        ["Publicação, testes e orientação para gestão"] = Row("Launch, testing and management guidance", "Publicación, pruebas y orientación de gestión", "الإطلاق والاختبار وإرشادات الإدارة"),
        ["Imersão e objetivos"] = Row("Discovery and goals", "Inmersión y objetivos", "الاستكشاف والأهداف"),
        ["Estrutura e protótipo"] = Row("Structure and prototype", "Estructura y prototipo", "الهيكل والنموذج الأولي"),
        ["Desenvolvimento e testes"] = Row("Development and testing", "Desarrollo y pruebas", "التطوير والاختبار"),
        ["Publicação e evolução"] = Row("Launch and evolution", "Publicación y evolución", "الإطلاق والتطوير"),
        ["Empresas, profissionais e novos negócios que precisam consolidar presença, apresentar serviços ou apoiar uma campanha."] = Row("Companies, professionals and new ventures that need to build presence, showcase services or support a campaign.", "Empresas, profesionales y nuevos negocios que necesitan consolidar presencia, presentar servicios o apoyar una campaña.", "الشركات والمهنيون والمشاريع الجديدة التي تحتاج إلى تعزيز حضورها أو عرض خدماتها."),
        ["Uma presença digital rápida, clara e preparada para transformar visitas em oportunidades."] = Row("A fast, clear digital presence built to turn visits into opportunities.", "Una presencia digital rápida y clara, preparada para convertir visitas en oportunidades.", "حضور رقمي سريع وواضح يحوّل الزيارات إلى فرص."),
        ["Eficiência operacional"] = Row("Operational efficiency", "Eficiencia operativa", "الكفاءة التشغيلية"),
        ["Automações Inteligentes"] = Row("Smart Automation", "Automatizaciones Inteligentes", "أتمتة ذكية"),
        ["Automatize processos, economize tempo e aumente a produtividade do seu negócio."] = Row("Automate processes, save time and increase business productivity.", "Automatice procesos, ahorre tiempo y aumente la productividad de su negocio.", "أتمت العمليات ووفر الوقت وارفع إنتاجية أعمالك."),
        ["Mapeamos tarefas repetitivas e conectamos ferramentas para reduzir trabalho manual, falhas operacionais e tempo gasto em rotinas que podem funcionar sozinhas."] = Row("We map repetitive tasks and connect tools to reduce manual work, operational errors and time spent on routines that can run themselves.", "Mapeamos tareas repetitivas y conectamos herramientas para reducir trabajo manual, errores operativos y tiempo invertido en rutinas automatizables.", "نحدد المهام المتكررة ونربط الأدوات لتقليل العمل اليدوي والأخطاء التشغيلية."),
        ["Mapeamento de processos e pontos de melhoria"] = Row("Process mapping and improvement opportunities", "Mapeo de procesos y oportunidades de mejora", "رسم العمليات وفرص التحسين"),
        ["Integrações entre sistemas, APIs e webhooks"] = Row("Integrations between systems, APIs and webhooks", "Integraciones entre sistemas, APIs y webhooks", "تكامل الأنظمة وواجهات API وخطافات الويب"),
        ["Fluxos automáticos, alertas e notificações"] = Row("Automated flows, alerts and notifications", "Flujos automáticos, alertas y notificaciones", "التدفقات الآلية والتنبيهات والإشعارات"),
        ["Logs, testes e documentação da operação"] = Row("Logs, testing and operational documentation", "Registros, pruebas y documentación operativa", "السجلات والاختبارات وتوثيق التشغيل"),
        ["Diagnóstico do fluxo"] = Row("Workflow diagnosis", "Diagnóstico del flujo", "تشخيص سير العمل"),
        ["Desenho da automação"] = Row("Automation design", "Diseño de la automatización", "تصميم الأتمتة"),
        ["Integração e validação"] = Row("Integration and validation", "Integración y validación", "التكامل والتحقق"),
        ["Monitoramento e ajustes"] = Row("Monitoring and refinement", "Monitoreo y ajustes", "المراقبة والتحسين"),
        ["Operações com tarefas recorrentes, informações duplicadas ou equipes dependentes de processos manuais."] = Row("Operations with recurring tasks, duplicated information or teams dependent on manual processes.", "Operaciones con tareas recurrentes, información duplicada o equipos dependientes de procesos manuales.", "عمليات تتضمن مهام متكررة أو معلومات مكررة أو اعتماداً على العمل اليدوي."),
        ["Processos mais previsíveis, menos retrabalho e mais tempo para decisões de maior valor."] = Row("More predictable processes, less rework and more time for high-value decisions.", "Procesos más predecibles, menos retrabajo y más tiempo para decisiones de mayor valor.", "عمليات أكثر قابلية للتنبؤ، وإعادة عمل أقل، ووقت أكبر للقرارات المهمة."),
        ["Produto e operação"] = Row("Product and operations", "Producto y operación", "المنتج والعمليات"),
        ["Sistemas Sob Medida"] = Row("Custom Systems", "Sistemas a Medida", "أنظمة مخصصة"),
        ["Soluções personalizadas para atender às necessidades específicas da sua empresa."] = Row("Custom solutions built around your company's specific needs.", "Soluciones personalizadas para las necesidades específicas de su empresa.", "حلول مخصصة تلبي احتياجات شركتك المحددة."),
        ["Desenvolvemos aplicações alinhadas às regras do seu negócio quando ferramentas prontas não acompanham o processo, a escala ou a experiência necessária."] = Row("We build applications around your business rules when off-the-shelf tools cannot support the required process, scale or experience.", "Desarrollamos aplicaciones alineadas con sus reglas de negocio cuando las herramientas estándar no cubren el proceso, la escala o la experiencia necesaria.", "نطور تطبيقات تتوافق مع قواعد عملك عندما لا تلبي الأدوات الجاهزة احتياجات العملية أو التوسع."),
        ["Painéis, portais e sistemas administrativos"] = Row("Dashboards, portals and administration systems", "Paneles, portales y sistemas administrativos", "لوحات المعلومات والبوابات وأنظمة الإدارة"),
        ["Regras de negócio, perfis e permissões"] = Row("Business rules, roles and permissions", "Reglas de negocio, perfiles y permisos", "قواعد العمل والأدوار والصلاحيات"),
        ["APIs, banco de dados e integrações"] = Row("APIs, databases and integrations", "APIs, bases de datos e integraciones", "واجهات API وقواعد البيانات والتكاملات"),
        ["Arquitetura evolutiva, testes e implantação"] = Row("Scalable architecture, testing and deployment", "Arquitectura evolutiva, pruebas e implementación", "بنية قابلة للتطور واختبارات ونشر"),
        ["Descoberta e requisitos"] = Row("Discovery and requirements", "Descubrimiento y requisitos", "الاستكشاف والمتطلبات"),
        ["Experiência e arquitetura"] = Row("Experience and architecture", "Experiencia y arquitectura", "التجربة والبنية"),
        ["Construção por etapas"] = Row("Phased development", "Construcción por etapas", "التطوير على مراحل"),
        ["Entrega e continuidade"] = Row("Delivery and continuity", "Entrega y continuidad", "التسليم والاستمرارية"),
        ["Negócios que precisam centralizar operações, substituir controles dispersos ou criar um produto digital próprio."] = Row("Businesses that need to centralise operations, replace scattered controls or create their own digital product.", "Negocios que necesitan centralizar operaciones, reemplazar controles dispersos o crear un producto digital propio.", "الأعمال التي تحتاج إلى توحيد العمليات أو استبدال الأدوات المتفرقة أو إنشاء منتج رقمي."),
        ["Uma solução segura e evolutiva, construída em torno da operação real da empresa."] = Row("A secure, scalable solution built around the company's real operation.", "Una solución segura y evolutiva, construida alrededor de la operación real de la empresa.", "حل آمن وقابل للتطور مبني حول التشغيل الفعلي للشركة."),

        ["Do conceito à"] = Row("From concept to", "Del concepto a la", "من الفكرة إلى"),
        ["experiência."] = Row("experience.", "experiencia.", "التجربة."),
        ["Explore algumas possibilidades de interfaces e experiências que podemos adaptar à identidade do seu negócio."] = Row("Explore interface and experience possibilities we can adapt to your business identity.", "Explore posibilidades de interfaces y experiencias que podemos adaptar a la identidad de su negocio.", "استكشف إمكانيات الواجهات والتجارب التي يمكننا تكييفها مع هوية عملك."),
        ["Explorar Ankh Lab"] = Row("Explore Ankh Lab", "Explorar Ankh Lab", "استكشف مختبر آنخ"),
        ["Projetos selecionados"] = Row("Selected projects", "Proyectos seleccionados", "مشاريع مختارة"),
        ["Projetos que transformam"] = Row("Projects that turn", "Proyectos que transforman", "مشاريع تحوّل"),
        ["desafios em caminhos."] = Row("challenges into paths.", "desafíos en caminos.", "التحديات إلى مسارات."),
        ["Estratégia, presença digital e produto trabalhando juntos para resolver operações reais."] = Row("Strategy, digital presence and product working together to solve real operations.", "Estrategia, presencia digital y producto trabajando juntos para resolver operaciones reales.", "الاستراتيجية والحضور الرقمي والمنتج تعمل معاً لحل عمليات حقيقية."),
        ["Projeto em produção"] = Row("Live project", "Proyecto en producción", "مشروع قيد التشغيل"),
        ["Site institucional"] = Row("Corporate website", "Sitio corporativo", "موقع مؤسسي"),
        ["Sistema SaaS"] = Row("SaaS system", "Sistema SaaS", "نظام SaaS"),
        ["Visitar site"] = Row("Visit website", "Visitar sitio", "زيارة الموقع"),
        ["Acessar sistema"] = Row("Open system", "Acceder al sistema", "فتح النظام"),
        ["Em desenvolvimento"] = Row("In development", "En desarrollo", "قيد التطوير"),
        ["Sobre a Ankh Digital"] = Row("About Ankh Digital", "Sobre Ankh Digital", "عن آنخ ديجيتال"),
        ["Ideias bem pensadas."] = Row("Ideas thoughtfully shaped.", "Ideas bien pensadas.", "أفكار مدروسة جيداً."),
        ["Tecnologia bem construída."] = Row("Technology built well.", "Tecnología bien construida.", "تقنية مبنية بإتقان."),
        ["Desenvolvemos sites, automações e sistemas sob medida, unindo estratégia, design e tecnologia para criar soluções que façam sentido para cada negócio."] = Row("We build websites, automation and custom systems, combining strategy, design and technology to create solutions that make sense for each business.", "Desarrollamos sitios, automatizaciones y sistemas a medida, uniendo estrategia, diseño y tecnología para crear soluciones relevantes para cada negocio.", "نطور مواقع وأتمتة وأنظمة مخصصة تجمع الاستراتيجية والتصميم والتقنية لصنع حلول تناسب كل عمل."),
        ["Descobrir"] = Row("Discover", "Descubrir", "اكتشاف"),
        ["Planejar"] = Row("Plan", "Planificar", "تخطيط"),
        ["Criar"] = Row("Create", "Crear", "إنشاء"),
        ["Entregar"] = Row("Deliver", "Entregar", "تسليم"),
        ["Evoluir"] = Row("Evolve", "Evolucionar", "تطوير"),
        ["Vamos construir juntos"] = Row("Let's build together", "Construyamos juntos", "لنبنِ معاً"),
        ["Tem uma ideia ou precisa de uma"] = Row("Have an idea or need a", "¿Tiene una idea o necesita una", "لديك فكرة أو تحتاج إلى"),
        ["solução digital?"] = Row("digital solution?", "solución digital?", "حل رقمي؟"),
        ["Conte o que sua empresa precisa e vamos conversar sobre a melhor solução."] = Row("Tell us what your business needs and let's discuss the best solution.", "Cuéntenos qué necesita su empresa y conversemos sobre la mejor solución.", "أخبرنا بما يحتاجه عملك ولنتحدث عن أفضل حل."),
        ["Falar sobre meu projeto"] = Row("Discuss my project", "Hablar sobre mi proyecto", "تحدث عن مشروعي"),
        ["Automações"] = Row("Automation", "Automatizaciones", "الأتمتة"),
        ["Sistemas"] = Row("Systems", "Sistemas", "الأنظمة"),
        ["Tecnologia com propósito, design com identidade."] = Row("Technology with purpose, design with identity.", "Tecnología con propósito, diseño con identidad.", "تقنية هادفة، وتصميم بهوية."),
        ["Navegação"] = Row("Navigation", "Navegación", "التنقل"),
        ["Todos os direitos reservados."] = Row("All rights reserved.", "Todos los derechos reservados.", "جميع الحقوق محفوظة."),
        ["Salvador · BA · Atendimento remoto para todo o Brasil"] = Row("Salvador · Bahia · Remote service across Brazil", "Salvador · Bahía · Atención remota en todo Brasil", "سلفادور · باهيا · خدمات عن بُعد في جميع أنحاء البرازيل"),

        ["Experimentos autorais"] = Row("Original experiments", "Experimentos originales", "تجارب أصلية"),
        ["Interfaces com identidades próprias."] = Row("Interfaces with identities of their own.", "Interfaces con identidad propia.", "واجهات بهوية خاصة."),
        ["O contexto muda. A atenção aos detalhes permanece."] = Row("The context changes. Attention to detail remains.", "El contexto cambia. La atención al detalle permanece.", "يتغير السياق ويبقى الاهتمام بالتفاصيل."),
        ["Experiências interativas"] = Row("Interactive experiences", "Experiencias interactivas", "تجارب تفاعلية"),
        ["Experiências que respondem ao usuário."] = Row("Experiences that respond to the user.", "Experiencias que responden al usuario.", "تجارب تستجيب للمستخدم."),
        ["Movimento, transições e interação transformam interfaces em experiências memoráveis."] = Row("Motion, transitions and interaction turn interfaces into memorable experiences.", "Movimiento, transiciones e interacción transforman interfaces en experiencias memorables.", "تحوّل الحركة والانتقالات والتفاعل الواجهات إلى تجارب لا تُنسى."),
        ["Experiência"] = Row("Experience", "Experiencia", "التجربة"),
        ["Uma forma mais envolvente de apresentar produtos, ambientes ou projetos."] = Row("A more engaging way to present products, spaces or projects.", "Una forma más atractiva de presentar productos, espacios o proyectos.", "طريقة أكثر جاذبية لعرض المنتجات أو المساحات أو المشاريع."),
        ["Elementos que respondem ao movimento e tornam a navegação mais imersiva."] = Row("Elements that respond to movement and make navigation more immersive.", "Elementos que responden al movimiento y hacen la navegación más inmersiva.", "عناصر تستجيب للحركة وتجعل التصفح أكثر غمراً."),
        ["Profundidade e movimento para transformar a apresentação de uma história."] = Row("Depth and motion to transform the way a story is presented.", "Profundidad y movimiento para transformar la presentación de una historia.", "العمق والحركة لتحويل طريقة تقديم قصة."),
        ["Role para explorar"] = Row("Scroll to explore", "Desplácese para explorar", "مرر للاستكشاف"),
        ["Microinterações"] = Row("Microinteractions", "Microinteracciones", "التفاعلات الدقيقة"),
        ["Pequenos detalhes. Grandes diferenças."] = Row("Small details. Big differences.", "Pequeños detalles. Grandes diferencias.", "تفاصيل صغيرة. فروق كبيرة."),
        ["Respostas visuais que tornam cada clique, seleção e ação mais intuitiva e agradável."] = Row("Visual responses that make every click, selection and action more intuitive and enjoyable.", "Respuestas visuales que hacen cada clic, selección y acción más intuitivos y agradables.", "استجابات بصرية تجعل كل نقرة واختيار وإجراء أكثر سهولة ومتعة."),
        ["Ankh Lab"] = Row("Ankh Lab", "Ankh Lab", "مختبر آنخ"),
        ["Laboratório interativo"] = Row("Interactive lab", "Laboratorio interactivo", "مختبر تفاعلي"),
        ["Não imagine como seu site pode ser."] = Row("Don't imagine what your website could be.", "No imagine cómo podría ser su sitio web.", "لا تتخيل كيف يمكن أن يكون موقعك."),
        ["Experimente."] = Row("Experience it.", "Experiméntelo.", "جرّبه."),
        ["Explore interfaces, animações e experiências interativas que podem inspirar e fazer parte do seu projeto."] = Row("Explore interfaces, animations and interactive experiences that can inspire and become part of your project.", "Explore interfaces, animaciones y experiencias interactivas que pueden inspirar y formar parte de su proyecto.", "استكشف الواجهات والرسوم المتحركة والتجارب التفاعلية التي يمكن أن تلهم مشروعك وتصبح جزءاً منه."),
        ["Experimentação digital"] = Row("Digital experimentation", "Experimentación digital", "تجارب رقمية"),
        ["Onde ideias viram"] = Row("Where ideas become", "Donde las ideas se vuelven", "حيث تتحول الأفكار إلى"),
        ["experiências."] = Row("experiences.", "experiencias.", "تجارب."),
        ["Interfaces, movimento e interação explorados além do convencional."] = Row("Interfaces, motion and interaction explored beyond convention.", "Interfaces, movimiento e interacción explorados más allá de lo convencional.", "واجهات وحركة وتفاعل تتجاوز المألوف."),
        ["Núcleo"] = Row("Core", "Núcleo", "النواة"),
        ["Interface"] = Row("Interface", "Interfaz", "واجهة"),
        ["Interação"] = Row("Interaction", "Interacción", "تفاعل"),
        ["Institucional"] = Row("Corporate", "Corporativo", "مؤسسي"),
        ["Saúde"] = Row("Health", "Salud", "الصحة"),
        ["Produto digital"] = Row("Digital product", "Producto digital", "منتج رقمي"),
        ["Comércio"] = Row("Commerce", "Comercio", "التجارة"),
        ["Transparência, profundidade e movimento para interfaces modernas."] = Row("Transparency, depth and motion for modern interfaces.", "Transparencia, profundidad y movimiento para interfaces modernas.", "شفافية وعمق وحركة لواجهات حديثة."),
        ["Movimento sutil e luz responsiva para destacar informações importantes."] = Row("Subtle motion and responsive light to highlight important information.", "Movimiento sutil y luz responsiva para destacar información importante.", "حركة خفيفة وإضاءة متجاوبة لإبراز المعلومات المهمة."),
        ["Clareza, confiança e sofisticação para negócios de alto valor."] = Row("Clarity, confidence and sophistication for high-value businesses.", "Claridad, confianza y sofisticación para negocios de alto valor.", "وضوح وثقة ورقي للأعمال عالية القيمة."),
        ["Uma experiência leve e acolhedora para saúde e bem-estar."] = Row("A light, welcoming experience for health and wellbeing.", "Una experiencia ligera y acogedora para salud y bienestar.", "تجربة خفيفة ومرحبة للصحة والعافية."),
        ["Indicadores e dados fictícios em uma interface de produto moderna."] = Row("Sample metrics and data in a modern product interface.", "Indicadores y datos ficticios en una interfaz de producto moderna.", "مؤشرات وبيانات تجريبية في واجهة منتج حديثة."),
        ["Produto, seleção e microinterações em uma experiência de compra conceitual."] = Row("Product, selection and microinteractions in a conceptual shopping experience.", "Producto, selección y microinteracciones en una experiencia de compra conceptual.", "منتج واختيار وتفاعلات دقيقة في تجربة تسوق مفاهيمية."),
        ["Interaja com o painel"] = Row("Interact with the panel", "Interactúe con el panel", "تفاعل مع اللوحة"),
        ["Mova o cursor sobre os cards"] = Row("Move the pointer over the cards", "Mueva el cursor sobre las tarjetas", "حرّك المؤشر فوق البطاقات"),
        ["Experimente o CTA"] = Row("Try the CTA", "Pruebe el CTA", "جرّب زر الإجراء"),
        ["Selecione um horário"] = Row("Select a time", "Seleccione un horario", "اختر موعداً"),
        ["Alterne o período do gráfico"] = Row("Change the chart period", "Cambie el período del gráfico", "غيّر فترة الرسم البياني"),
        ["Escolha o acabamento e adicione"] = Row("Choose a finish and add it", "Elija el acabado y añádalo", "اختر التشطيب وأضفه"),
        ["Visão geral"] = Row("Overview", "Vista general", "نظرة عامة"),
        ["Projetos ativos"] = Row("Active projects", "Proyectos activos", "المشاريع النشطة"),
        ["Eficiência"] = Row("Efficiency", "Eficiencia", "الكفاءة"),
        ["Estável"] = Row("Stable", "Estable", "مستقر"),
        ["Visão semanal"] = Row("Weekly overview", "Vista semanal", "نظرة أسبوعية"),
        ["Fluxo criativo"] = Row("Creative flow", "Flujo creativo", "التدفق الإبداعي"),
        ["Ativo"] = Row("Live", "Activo", "نشط"),
        ["Progresso"] = Row("Progress", "Progreso", "التقدم"),
        ["Foco"] = Row("Focus", "Enfoque", "التركيز"),
        ["Entregas"] = Row("Deliveries", "Entregas", "التسليمات"),
        ["Ritmo"] = Row("Pace", "Ritmo", "الإيقاع"),
        ["Seu melhor ritmo aparece entre 09h e 12h."] = Row("Your best rhythm appears between 9 am and noon.", "Su mejor ritmo aparece entre las 9 y las 12.", "أفضل إيقاع لك يظهر بين التاسعة صباحاً والظهر."),
        ["Ocultar análise"] = Row("Hide analysis", "Ocultar análisis", "إخفاء التحليل"),
        ["Ver análise"] = Row("View analysis", "Ver análisis", "عرض التحليل"),
        ["Estratégia & Governança"] = Row("Strategy & Governance", "Estrategia y Gobernanza", "الاستراتيجية والحوكمة"),
        ["Decisões precisas."] = Row("Precise decisions.", "Decisiones precisas.", "قرارات دقيقة."),
        ["Crescimento consistente."] = Row("Consistent growth.", "Crecimiento constante.", "نمو مستدام."),
        ["Orientação estratégica para negócios que valorizam clareza, confiança e visão de longo prazo."] = Row("Strategic guidance for businesses that value clarity, confidence and long-term vision.", "Orientación estratégica para negocios que valoran claridad, confianza y visión a largo plazo.", "توجيه استراتيجي للأعمال التي تقدر الوضوح والثقة والرؤية طويلة المدى."),
        ["Conheça nossa abordagem"] = Row("Explore our approach", "Conozca nuestro enfoque", "اكتشف نهجنا"),
        ["Atendimento disponível"] = Row("Appointments available", "Atención disponible", "المواعيد متاحة"),
        ["Cuidado que acompanha você"] = Row("Care that stays with you", "Cuidado que le acompaña", "رعاية ترافقك"),
        ["Movimento com mais leveza."] = Row("Move with greater ease.", "Movimiento con más ligereza.", "حركة بمزيد من الراحة."),
        ["Um espaço conceitual para acolher, orientar e recuperar o seu bem-estar."] = Row("A conceptual space to welcome, guide and restore your wellbeing.", "Un espacio conceptual para acoger, orientar y recuperar su bienestar.", "مساحة مفاهيمية للاحتواء والتوجيه واستعادة عافيتك."),
        ["especialidades"] = Row("specialities", "especialidades", "تخصصاً"),
        ["avaliação fictícia"] = Row("sample rating", "valoración ficticia", "تقييم تجريبي"),
        ["Serviço em destaque"] = Row("Featured service", "Servicio destacado", "خدمة مميزة"),
        ["Avaliação funcional"] = Row("Functional assessment", "Evaluación funcional", "تقييم وظيفي"),
        ["Escolha um horário para visualizar a experiência:"] = Row("Choose a time to preview the experience:", "Elija un horario para ver la experiencia:", "اختر موعداً لمعاينة التجربة:"),
        ["Agendar demonstração"] = Row("Schedule demo", "Agendar demostración", "حجز العرض"),
        ["Todos os sistemas operacionais"] = Row("All systems operational", "Todos los sistemas operativos", "جميع الأنظمة تعمل"),
        ["Receita simulada"] = Row("Simulated revenue", "Ingresos simulados", "إيرادات تجريبية"),
        ["Usuários ativos"] = Row("Active users", "Usuarios activos", "المستخدمون النشطون"),
        ["Conversão"] = Row("Conversion", "Conversión", "التحويل"),
        ["Atividade"] = Row("Activity", "Actividad", "النشاط"),
        ["Dados ilustrativos"] = Row("Illustrative data", "Datos ilustrativos", "بيانات توضيحية"),
        ["Nova coleção"] = Row("New collection", "Nueva colección", "مجموعة جديدة"),
        ["Objetos essenciais"] = Row("Essential objects", "Objetos esenciales", "قطع أساسية"),
        ["Iluminação suave e presença escultórica para transformar pequenos espaços."] = Row("Soft lighting and sculptural presence to transform small spaces.", "Iluminación suave y presencia escultórica para transformar espacios pequeños.", "إضاءة ناعمة وحضور نحتي لتحويل المساحات الصغيرة."),
        ["valor fictício"] = Row("sample price", "valor ficticio", "سعر تجريبي"),
        ["Acabamento:"] = Row("Finish:", "Acabado:", "التشطيب:"),
        ["Areia"] = Row("Sand", "Arena", "رملي"),
        ["Terracota"] = Row("Terracotta", "Terracota", "تيراكوتا"),
        ["Grafite"] = Row("Graphite", "Grafito", "جرافيت"),
        ["Adicionar"] = Row("Add", "Añadir", "إضافة"),
        ["Adicionado ✓"] = Row("Added ✓", "Añadido ✓", "تمت الإضافة ✓"),
        ["Interação demonstrativa — nenhum carrinho foi criado."] = Row("Demo interaction — no basket was created.", "Interacción de demostración: no se creó ningún carrito.", "تفاعل توضيحي — لم يتم إنشاء سلة."),
        ["Botões inteligentes"] = Row("Smart buttons", "Botones inteligentes", "أزرار ذكية"),
        ["Respostas que acompanham intenção, ação e conclusão."] = Row("Responses that follow intent, action and completion.", "Respuestas que acompañan intención, acción y conclusión.", "استجابات تواكب النية والإجراء والإنجاز."),
        ["Inputs modernos"] = Row("Modern inputs", "Campos modernos", "حقول حديثة"),
        ["Contexto, validação e segurança no momento certo."] = Row("Context, validation and security at the right moment.", "Contexto, validación y seguridad en el momento adecuado.", "سياق وتحقق وأمان في الوقت المناسب."),
        ["Toggle & seleção"] = Row("Toggle & selection", "Interruptor y selección", "التبديل والاختيار"),
        ["Escolhas claras com confirmação visual imediata."] = Row("Clear choices with immediate visual confirmation.", "Opciones claras con confirmación visual inmediata.", "خيارات واضحة مع تأكيد بصري فوري."),
        ["Cards responsivos ao cursor"] = Row("Pointer-responsive cards", "Tarjetas responsivas al cursor", "بطاقات تستجيب للمؤشر"),
        ["Luz, borda e profundidade orientadas pelo movimento."] = Row("Light, borders and depth guided by movement.", "Luz, bordes y profundidad guiados por el movimiento.", "ضوء وحدود وعمق تستجيب للحركة."),
        ["Feedback de ação"] = Row("Action feedback", "Feedback de acción", "استجابة الإجراء"),
        ["O usuário sempre sabe o que está acontecendo."] = Row("The user always knows what is happening.", "El usuario siempre sabe qué está ocurriendo.", "يعرف المستخدم دائماً ما يحدث."),
        ["Menu / navegação"] = Row("Menu / navigation", "Menú / navegación", "القائمة / التنقل"),
        ["Orientação visual entre opções e contextos."] = Row("Visual guidance across options and contexts.", "Orientación visual entre opciones y contextos.", "توجيه بصري بين الخيارات والسياقات."),
        ["Processando"] = Row("Processing", "Procesando", "جارٍ المعالجة"),
        ["Concluído"] = Row("Complete", "Completado", "مكتمل"),
        ["Explorar agora"] = Row("Explore now", "Explorar ahora", "استكشف الآن"),
        ["Clique para acompanhar todos os estados"] = Row("Click to follow every state", "Haga clic para ver todos los estados", "انقر لمتابعة جميع الحالات"),
        ["E-mail profissional"] = Row("Work email", "Correo profesional", "البريد المهني"),
        ["Senha"] = Row("Password", "Contraseña", "كلمة المرور"),
        ["Ocultar"] = Row("Hide", "Ocultar", "إخفاء"),
        ["Mostrar"] = Row("Show", "Mostrar", "إظهار"),
        ["Notificações"] = Row("Notifications", "Notificaciones", "الإشعارات"),
        ["Atualizações importantes"] = Row("Important updates", "Actualizaciones importantes", "تحديثات مهمة"),
        ["Direção para decisões mais claras."] = Row("Direction for clearer decisions.", "Dirección para decisiones más claras.", "توجيه لقرارات أوضح."),
        ["Soluções que respondem ao contexto."] = Row("Solutions that respond to context.", "Soluciones que responden al contexto.", "حلول تستجيب للسياق."),
        ["Escreva uma mensagem"] = Row("Write a message", "Escriba un mensaje", "اكتب رسالة"),
        ["Enviando"] = Row("Sending", "Enviando", "جارٍ الإرسال"),
        ["Enviar mensagem"] = Row("Send message", "Enviar mensaje", "إرسال الرسالة"),
        ["Mensagem enviada"] = Row("Message sent", "Mensaje enviado", "تم إرسال الرسالة"),
        ["Recebemos sua solicitação."] = Row("We received your request.", "Recibimos su solicitud.", "تلقينا طلبك."),
        ["Menu compacto"] = Row("Compact menu", "Menú compacto", "قائمة مدمجة"),
        ["Componentes"] = Row("Components", "Componentes", "المكونات"),
        ["Digite para ver a validação"] = Row("Type to see validation", "Escriba para ver la validación", "اكتب لرؤية التحقق"),
        ["E-mail válido"] = Row("Valid email", "Correo válido", "بريد صالح"),
        ["Informe um e-mail válido"] = Row("Enter a valid email", "Ingrese un correo válido", "أدخل بريداً صالحاً"),
        ["Explore o Lab"] = Row("Explore the lab", "Explore el laboratorio", "استكشف المختبر"),
        ["Interfaces"] = Row("Interfaces", "Interfaces", "واجهات"),
        ["Interatividade"] = Row("Interactivity", "Interactividad", "التفاعلية"),
        ["Painéis visuais que revelam novas informações conforme o usuário interage."] = Row("Visual panels that reveal new information as the user interacts.", "Paneles visuales que revelan nueva información a medida que el usuario interactúa.", "لوحات مرئية تكشف معلومات جديدة أثناء تفاعل المستخدم."),
        ["Mova o cursor sobre os painéis"] = Row("Move the pointer over the panels", "Mueva el cursor sobre los paneles", "حرّك المؤشر فوق اللوحات"),
        ["Toque nos painéis"] = Row("Tap the panels", "Toque los paneles", "المس اللوحات"),
        ["Painéis visuais interativos"] = Row("Interactive visual panels", "Paneles visuales interactivos", "لوحات مرئية تفاعلية"),
        ["Arquitetura"] = Row("Architecture", "Arquitectura", "العمارة"),
        ["Apresente projetos e ambientes com uma experiência visual mais envolvente."] = Row("Present projects and spaces with a more engaging visual experience.", "Presente proyectos y espacios con una experiencia visual más atractiva.", "اعرض المشاريع والمساحات بتجربة بصرية أكثر جاذبية."),
        ["Explorar"] = Row("Explore", "Explorar", "استكشف"),
        ["Hospitalidade"] = Row("Hospitality", "Hospitalidad", "الضيافة"),
        ["Transforme espaços, destinos e experiências em uma apresentação memorável."] = Row("Turn spaces, destinations and experiences into a memorable presentation.", "Transforme espacios, destinos y experiencias en una presentación memorable.", "حوّل المساحات والوجهات والتجارب إلى عرض لا يُنسى."),
        ["Descobrir"] = Row("Discover", "Descubrir", "اكتشف"),
        ["Interiores"] = Row("Interiors", "Interiores", "التصميم الداخلي"),
        ["Destaque detalhes, ambientes e coleções sem sobrecarregar a interface."] = Row("Highlight details, environments and collections without overloading the interface.", "Destaque detalles, ambientes y colecciones sin sobrecargar la interfaz.", "أبرز التفاصيل والمساحات والمجموعات دون إثقال الواجهة."),
        ["Conhecer"] = Row("Learn more", "Conocer", "تعرّف"),
        ["Uma galeria expansível que transforma imagens em uma navegação visual dinâmica e imersiva."] = Row("An expandable gallery that turns images into dynamic, immersive visual navigation.", "Una galería ampliable que transforma imágenes en una navegación visual dinámica e inmersiva.", "معرض قابل للتوسيع يحوّل الصور إلى تنقل بصري ديناميكي وغامر."),
        ["Passe o cursor ou selecione um destino"] = Row("Hover or select a destination", "Pase el cursor o seleccione un destino", "مرر المؤشر أو اختر وجهة"),
        ["Toque em um destino para explorar"] = Row("Tap a destination to explore", "Toque un destino para explorar", "المس وجهة للاستكشاف"),
        ["Galeria expansível de destinos"] = Row("Expandable destination gallery", "Galería ampliable de destinos", "معرض وجهات قابل للتوسيع"),
        ["Portão 04 — Japão"] = Row("Gate 04 — Japan", "Puerta 04 — Japón", "البوابة 04 — اليابان"),
        ["Templos históricos, jardins silenciosos e uma atmosfera que combina tradição e contemplação."] = Row("Historic temples, quiet gardens and an atmosphere that blends tradition and contemplation.", "Templos históricos, jardines silenciosos y una atmósfera que combina tradición y contemplación.", "معابد تاريخية وحدائق هادئة وأجواء تمزج بين التقاليد والتأمل."),
        ["Portão 11 — Grécia"] = Row("Gate 11 — Greece", "Puerta 11 — Grecia", "البوابة 11 — اليونان"),
        ["Arquitetura branca, mar Egeu e paisagens marcadas por alguns dos pores do sol mais conhecidos do Mediterrâneo."] = Row("White architecture, the Aegean Sea and landscapes shaped by some of the Mediterranean's best-known sunsets.", "Arquitectura blanca, mar Egeo y paisajes marcados por algunas de las puestas de sol más conocidas del Mediterráneo.", "عمارة بيضاء وبحر إيجه ومناظر تشتهر ببعض من أشهر غروب الشمس في البحر المتوسط."),
        ["Portão 07 — Islândia"] = Row("Gate 07 — Iceland", "Puerta 07 — Islandia", "البوابة 07 — آيسلندا"),
        ["Paisagens vulcânicas, águas termais e noites onde a aurora boreal transforma completamente o horizonte."] = Row("Volcanic landscapes, thermal waters and nights when the northern lights transform the horizon.", "Paisajes volcánicos, aguas termales y noches en las que la aurora boreal transforma completamente el horizonte.", "مناظر بركانية ومياه حرارية وليالٍ تحوّل فيها الأضواء الشمالية الأفق تماماً."),
        ["Portão 02 — Marrocos"] = Row("Gate 02 — Morocco", "Puerta 02 — Marruecos", "البوابة 02 — المغرب"),
        ["Mercados, arquitetura, cores e texturas criando uma experiência visual intensa no coração de Marrocos."] = Row("Markets, architecture, colour and texture creating an intense visual experience in the heart of Morocco.", "Mercados, arquitectura, colores y texturas creando una experiencia visual intensa en el corazón de Marruecos.", "أسواق وعمارة وألوان وملامس تخلق تجربة بصرية مكثفة في قلب المغرب."),
        ["Explorar destino"] = Row("Explore destination", "Explorar destino", "استكشف الوجهة"),
    };

    public Language Current { get; private set; } = Languages[0];
    public event Action? Changed;

    public string T(string source)
        => Current.Code == "pt" ? source : Translations.TryGetValue(source, out var row) && row.TryGetValue(Current.Code, out var value) ? value : source;

    public string F(string source, params object[] args) => string.Format(T(source), args);

    public async ValueTask InitializeAsync()
    {
        var code = await js.InvokeAsync<string>("ankhLanguage.initialize", Languages.Select(language => language.Code).ToArray());
        await ApplyAsync(code, false);
    }

    public ValueTask SetAsync(string code) => ApplyAsync(code, true);

    private async ValueTask ApplyAsync(string code, bool persist)
    {
        var language = Languages.FirstOrDefault(item => item.Code == code) ?? Languages[0];
        var changed = language != Current;
        Current = language;
        await js.InvokeVoidAsync("ankhLanguage.apply", language.Code, language.Locale, language.RightToLeft, persist);
        if (changed) Changed?.Invoke();
    }

    private static Dictionary<string, string> Row(string english, string spanish, string arabic) => new()
    {
        ["en"] = english,
        ["es"] = spanish,
        ["ar"] = arabic
    };
}
